services:
  - type: web
    name: enginex-api
    env: node
    region: oregon
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://enginex-seven.vercel.app
      - key: NODE_ENV
        value: production
